const PROMPT_GENERATION_MIN_COUNT = 3;
const PROMPT_GENERATION_MAX_COUNT = 100;
const PROMPT_GENERATION_BATCH_SIZE = 20;

module.exports = {
  PROMPT_GENERATION_MIN_COUNT,
  PROMPT_GENERATION_MAX_COUNT,
  PROMPT_GENERATION_BATCH_SIZE
};
